from scholarly import scholarly
import time

# Lista de artigos
artigos = [
    "Hughes G (1968) On the mean accuracy of statistical pattern recognizers.",
    "Keogh E, Mueen A (2010) Curse of dimensionality.",
    "Ye H, Sugihara G (2016) Information leverage in interconnected ecosystems: overcoming the curse of dimensionality.",
    "Ding SF et al (2012) A survey on feature extraction for pattern recognition.",
    "Cunningham JP, Yu BM (2014) Dimensionality reduction for large-scale neural recordings.",
    "Cunningham JP, Ghahramani Z (2015) Linear dimensionality reduction: survey, insights, and generalizations.",
    "Ornek C, Vural E (2019) Nonlinear supervised dimensionality reduction via smooth regular embeddings.",
    "Silva R, Melo-Pinto P (2021) A review of different dimensionality reduction methods for the prediction of sugar content from hyperspectral images of wine grape berries.",
    "Aziz R, Verma CK, Srivastava N (2017) Dimension reduction methods for microarray data: a review.",
    "Zebari R et al (2020) A comprehensive review of dimensionality reduction techniques for feature selection and feature extraction.",
    "Aziz R, Verma CK, Srivastava N (2018) Artificial neural network classification of high dimensional data with novel optimization approach of dimension reduction.",
    "Chandrashekar G, Sahin F (2014) A survey on feature selection methods.",
    "Dash M, Liu H (1997) Feature selection for classification.",
    "Dash M, Liu H, Yao J (1997) Dimensionality reduction of unsupervised data.",
    "Hu J (2008) Survey on feature dimension reduction for high-dimensional data.",
    "Hira ZM, Gillies DF (2015) A review of feature selection and feature extraction methods applied on microarray data.",
    "Hua JP, Tembe WD, Dougherty ER (2009) Performance of feature-selection methods in the classification of high-dimension data.",
    "Welch WJ (1982) Branch-and-bound search for experimental designs based on D optimality and other criteria.",
    "Wang JH et al (2016) Analysis of imbalanced weather data based on branch-and-bound approach.",
    "Gokce A, Hsiao K-T, Advani SG (2002) Branch and bound search to optimize injection gate locations in liquid composite molding processes.",
    "Ow PS, Morton TE (1988) Filtered beam search in scheduling.",
    "Kumar A et al (2013) Beam search algorithms for multilabel learning.",
    "Araya I, Riff M-C (2014) A beam search approach to the container loading problem.",
    "Wang SJ, Xi LF, Zhou BH (2007) Filtered-beam-search-based algorithm for dynamic rescheduling in FMS.",
    "Peng H, Long F, Ding C (2005) Feature selection based on mutual information criteria of max-dependency, max-relevance, and min-redundancy.",
    "Cotter SF et al (1999) Forward sequential algorithms for best basis selection.",
    "Pereira RD et al (2013) Modified sequential forward selection applied to predicting septic shock outcome in the intensive care unit.",
    "Korf RE (1985) Depth-first iterative-deepening: an optimal admissible tree search.",
    "Lo WY, Zwicker M (2010) Bidirectional search for interactive motion synthesis.",
    "Kaindl H, Kainz G (1997) Bidirectional heuristic search reconsidered.",
    "Zhou J, Müller M (2004) Solving systems of difference constraints incrementally with bidirectional search.",
    "Jia W, Zhao D, Ding L (2016) An optimized RBF neural network algorithm based on partial least squares and genetic algorithm for classification of small sample.",
    "Ruiz GR et al (2016) Genetic algorithm for building envelope calibration.",
    "Pezzella F, Morganti G, Ciaschetti G (2008) A genetic algorithm for the flexible job-shop scheduling problem.",
    "Rostami M et al (2021) Review of swarm intelligence-based feature selection methods.",
    "Jordehi AR, Jasni J (2015) Particle swarm optimisation for discrete optimisation problems: a review.",
    "Eroğlu Y, Seçkiner SU (2012) Design of wind farm layout using ant colony algorithm.",
    "He J, Hou Z (2012) Ant colony algorithm for traffic signal timing optimization.",
    "Reed M, Yiannakou A, Evering R (2014) An ant colony algorithm for the multi-compartment vehicle routing problem.",
    "Mao Y et al (2007) Survey for study of feature selection algorithms.",
    "Narendra PM, Fukunaga K (1977) A branch and bound algorithm for feature subset selection.",
    "Zhang HB, Sun GY (1999) Tabu search algorithm for feature selection.",
    "Zhang X (1998) Dynamic programming method for feature selection.",
    "Lewis DD (1992) An evaluation of phrasal and clustered representations on a text categorization task.",
    "Simek K et al (2004) Using SVD and SVM methods for selection, classification, clustering and modeling of DNA microarray data.",
    "Fujarewicz K, Wiench M (2003) Selecting differentially expressed genes for colon tumor classification.",
    "Mishra D, Sharma S (2021) Performance analysis of dimensionality reduction techniques: a comprehensive review.",
    "Moore B (1981) Principal component analysis in linear systems: controllability, observability, and model reduction.",
    "Abdi H, Williams LJ (2010) Principal component analysis.",
    "Qiang LI et al (2005) Online palmprint identification based on improved 2D PCA.",
    "Senkov O et al (2015) Accelerated exploration of multi-principal element alloys with solid solution phases.",
    "Song F et al (2008) A highly scalable incremental facial feature extraction method.",
    "Wang S et al (2016) Semi-supervised linear discriminant analysis for dimension reduction and classification.",
    "Jin Z et al (2001) Face recognition based on the uncorrelated discriminant transformation.",
    "Dehak N et al (2010) Front-end factor analysis for speaker verification.",
    "Comon P (1994) Independent component analysis, a new concept?",
    "Hyvärinen A, Oja E (2000) Independent component analysis: algorithms and applications.",
    "Huang QH, Wang S, Liu Z (2007) Improved algorithm of image feature extraction based on independent component analysis.",
    "Yuen PC, Lai J-H (2002) Face representation using independent component analysis.",
    "Wang J, Chang C-I (2006) Independent component analysis-based dimensionality reduction with applications in hyperspectral image analysis.",
    "Kong W et al (2008) A review of independent component analysis application to microarray gene expression data.",
    "Musheer RA, Verma C, Srivastava N (2019) Novel machine learning approach for classification of high-dimensional microarray data.",
    "Beatty M, Manjunath B (1997) Dimensionality reduction using multi-dimensional scaling for content-based retrieval.",
    "Cambria E, Mazzocco T, Hussain A (2013) Application of multi-dimensional scaling and artificial neural networks for biologically inspired opinion mining.",
    "Dzidolikaitė A (2015) Genetic algorithms for multidimensional scaling.",
    "Wall ME, Rechtsteiner A, Rocha LM (2003) Singular value decomposition and principal component analysis.",
    "Chen Y et al (2018) Application of singular value decomposition algorithm to dimension-reduced clustering analysis of daily load profiles.",
    "Kang M, Kim JM (2013) Singular value decomposition based feature extraction approaches for classifying faults of induction motors.",
    "Yang J (2005) KPCA plus LDA: a complete kernel Fisher discriminant framework for feature extraction and recognition.",
    "Mika S et al (1999) Fisher discriminant analysis with kernels.",
    "Zhu X et al (2012) Dimensionality reduction by mixed kernel canonical correlation analysis.",
    "Lee DD et al (1999) Learning the parts of objects by non-negative matrix factorization.",
    "Wang Y et al (2005) Non-negative matrix factorization framework for face recognition.",
    "Lee CW et al (2003) Font classification using NMF.",
    "Pauca VP, Piper J, Plemmons RJ (2006) Nonnegative matrix factorization for spectral data analysis.",
    "Liu W, Yuan K, Ye D (2008) Reducing microarray data via nonnegative matrix factorization for visualization and clustering analysis.",
    "Shannon CE (1948) A mathematical theory of communication.",
    "Quiroga RQ, Panzeri S (2009) Extracting information from neuronal populations: information theory and decoding approaches.",
    "ShiZhong L, XiaoJun J, SuLei Z (1999) The application study of entropy analysis method in feature extraction.",
    "Ding S, Jin F, Wang X (2005) Information feature compression algorithm based on SCEC.",
    "Daubechies I (2009) The wavelet transform, time-frequency localization and signal analysis.",
    "Bruce LM, Koger CH, Li J (2002) Dimensionality reduction of hyperspectral data using discrete wavelet transform feature extraction.",
    "Zhang J, Zhang B, Jiang X-Z (2000) Analyses of feature extraction methods based on wavelet transform.",
    "He H, Starzyk JA (2005) A self-organizing learning array system for power quality classification based on wavelet transform.",
    "Hamaneh MB et al (2013) Automated removal of EKG artifact from EEG data using independent component analysis and continuous wavelet transformation.",
    "Jones MC, Sibson R (1987) What is projection pursuit?",
    "Durvaux F et al (2015) Efficient selection of time samples for higher-order DPA with projection pursuits.",
    "Gao MT, Wang ZO (2007) A new algorithm for text clustering based on projection pursuit.",
    "Law MH, Jain AK (2006) Incremental nonlinear dimensionality reduction by manifold learning.",
    "Raducanu B, Dornaika F (2012) A supervised non-linear dimensionality reduction approach for manifold learning.",
    "Olson CC, Judd KP, Nichols JM (2018) Manifold learning techniques for unsupervised anomaly detection.",
    "Balasubramanian M et al (2002) The isomap algorithm and topological stability.",
    "Zhang Z, Chow TW, Zhao M (2012) M-Isomap: Orthogonal constrained marginal isomap for nonlinear dimensionality reduction.",
    "Tenenbaum JB, De Silva V, Langford JC (2000) A global geometric framework for nonlinear dimensionality reduction.",
    "Roweis ST, Saul LK (2000) Nonlinear dimensionality reduction by locally linear embedding.",
    "Pan Y, Ge SS, Al Mamun A (2009) Weighted locally linear embedding for dimension reduction.",
    "Chen J, Liu Y (2011) Locally linear embedding: a survey.",
    "Ge SS, He H, Shen C (2012) Geometrically local embedding in manifolds for dimension reduction.",
    "Yin FP (2012) Based on improved LLE and FSVM method in face recognition of application.",
    "De Ridder D et al (2003) Supervised locally linear embedding.",
    "Zhang S-Q (2009) Enhanced supervised locally linear embedding.",
    "Wang H et al (2006) Application of dimension reduction on using improved LLE based on clustering.",
    "He X, Niyogi P (2003) Locality preserving projections.",
    "Kokiopoulou E, Saad Y (2007) Orthogonal neighborhood preserving projections: A projection-based dimensionality reduction technique.",
    "Wong WK, Zhao H (2012) Supervised optimal locality preserving projection.",
    "Li W et al (2011) Locality-preserving dimensionality reduction and classification for hyperspectral image analysis.",
    "Jiang R et al (2016) Dimensionality reduction on anchorgraph with an efficient locality preserving projection.",
    "Shen Z-H, Pan Y-H, Wang S (2008) A supervised locality preserving projection algorithm for dimensionality reduction.",
    "Shikkenawis G, Mitra SK (2016) On some variants of locality preserving projection.",
    "Zhan YB (2011) Research on manifold learning theories, methods and applications.",
    "Ding S et al (2004) New PCA feature compression algorithm based on information theory.",
    "Ding S, Jin F, Wang J (2003) Information feature analysis and selection of orthogonal transformation.",
    "Fei Z, With P (2005) Facial feature extraction using a cascade of model-based algorithms.",
    "Nabti M, Bouridane A (2008) An effective and fast iris recognition system based on a combined multiscale feature extraction technique.",
    "Ji S, Ye J (2008) Generalized linear discriminant analysis: a unified framework and efficient model selection.",
    "Tibshirani R (1996) Regression shrinkage and selection via the Lasso.",
    "Rodriguez JD, Perez A, Lozano JA (2009) Sensitivity analysis of k-fold cross validation in prediction error estimation.",
    "Bhadra A et al (2019) Lasso meets horseshoe: a survey.",
    "Kohannim O et al (2012) Discovery and replication of gene influences on brain structure using LASSO regression.",
    "Chen LF et al (2000) A new LDA-based face recognition system which can solve the small sample size problem.",
    "Huang R (2007) A margin based feature extraction algorithm for the small sample size problem.",
    "Lu J et al (2020) Learning from very few samples: a survey.",
    "Wang Y et al (2020) Generalizing from a few examples: A survey on few-shot learning.",
    "Hertz T, Hillel AB, Weinshall D (2006) Learning a kernel function for classification with small training samples.",
    "Aziz R, Verma CK, Srivastava N (2017) A novel approach for dimension reduction of microarray.",
    "Aziz R et al (2017) Artificial neural network classification of microarray data using new hybrid gene selection method.",
    "Hinton GE, Salakhutdinov RR (2006) Reducing the dimensionality of data with neural networks.",
    "Hinton GE, Osindero S, Teh YW (2014) A fast learning algorithm for deep belief nets.",
    "Arel I, Rose DC, Karnowski TP (2010) Deep machine learning—a new frontier in artificial intelligence research.",
    "Yi S, Wang X, Tang X (2014) Deep learning face representation by joint identification-verification.",
    "Wen W et al (2016) Learning structured sparsity in deep neural networks.",
    "Yu K et al (2013) Deep learning: yesterday, today, and tomorrow.",
    "Traore BB, Kamsu-Foguem B, Tangara F (2018) Deep convolution neural network for image recognition.",
    "Al-Saffar AAM, Tao H, Talab MA (2017) Review of deep convolution neural network in image classification.",
    "Yang J, Li J (2017) Application of deep convolution neural network.",
    "He K et al (2016) Deep residual learning for image recognition.",
    "Ren S et al (2015) Faster r-cnn: Towards real-time object detection with region proposal networks.",
    "He K et al (2017) Mask r-cnn.",
    "Yu F, Koltun V (2015) Multi-scale context aggregation by dilated convolutions.",
    "Cui L et al (2020) Context-aware block net for small object detection.",
    "Zhang Z, Wang X, Jung C (2018) DCSR: Dilated convolutions for single image super-resolution.",
    "Zaremba W, Sutskever I, Vinyals O (2014) Recurrent neural network regularization.",
    "Lipton ZC, Berkowitz J, Elkan C (2015) A critical review of recurrent neural networks for sequence learning.",
    "Jozefowicz R, Zaremba W, Sutskever I (2015) An empirical exploration of recurrent network architectures.",
    "Yu Y et al (2019) A review of recurrent neural networks: LSTM cells and network architectures.",
    "Koutnik J et al (2014) A clockwork rnn.",
    "Cho K et al (2014) Learning phrase representations using RNN encoder-decoder for statistical machine translation.",
    "Ergen T, Mirza AH, Kozat SS (2019) Energy-efficient LSTM networks for online learning.",
    "Vaswani A et al (2017) Attention is all you need.",
    "Wang W et al (2021) Pyramid vision transformer: a versatile backbone for dense prediction without convolutions.",
    "Yang J et al (2021) Focal self-attention for local-global interactions in vision transformers.",
    "Han K et al (2021) Transformer in transformer.",
    "Srinivas A et al (2021) Bottleneck transformers for visual recognition.",
    "Rumelhart DE, Hinton GE, Williams RJ (1985) Learning internal representations by error propagation.",
    "Hinton GE, Salakhutdinov RR (2006) Reducing the dimensionality of data with neural networks.",
    "Dong G et al (2018) A review of the autoencoder and its variants: a comparative perspective from target recognition in synthetic-aperture radar images.",
    "Liu T et al (2017) NIRS feature extraction based on deep auto-encoder neural network.",
    "Song W et al (2021) A new deep auto-encoder using multi-scale reconstruction errors and weight update correlation.",
    "Hinton GE (2009) Deep belief networks.",
    "Roder M et al (2021) Reinforcing learning in Deep Belief Networks through nature-inspired optimization.",
    "Kuremoto T et al (2014) Time series forecasting using a deep belief network with restricted Boltzmann machines.",
    "Hassan MM et al (2018) Human emotion recognition using deep belief network architecture.",
    "Gogna A, Majumdar A (2016) Semi supervised autoencoder.",
    "Lee DH (2013) Pseudo-label: The simple and efficient semi-supervised learning method for deep neural networks.",
    "Lu S, Chen Z, Xu B (2014) Learning new semi-supervised deep auto-encoder features for statistical machine translation.",
    "Li Z, Ko B, Choi H-J (2019) Naive semi-supervised deep learning using pseudo-label.",
    "Wu H, Prasad S (2017) Semi-supervised deep learning using pseudo labels for hyperspectral image classification.",
    "Sainath TN et al (2015) Convolutional, long short-term memory, fully connected deep neural networks.",
    "Seide F et al (2011) Feature engineering in context-dependent deep neural networks for conversational speech transcription.",
    "Li J et al (2012) Improving wideband speech recognition using mixed-bandwidth training data in CD-DNN-HMM.",
    "Schmidhuber J (2015) Deep learning in neural networks: an overview.",
    "Lecun Y, Bengio Y, Hinton G (2015) Deep learning.",
    "Lngkvist M, Karlsson L, Loutfi A (2014) A review of unsupervised feature learning and deep learning for time-series modeling."
]

def buscar_link(artigo):
    search_query = scholarly.search_pubs(artigo)
    result = next(search_query)

    #scholarly.pprint(result)

    pub_url = result.get('pub_url')
    name = result.get('bib', {}).get('title')

    print(f"{name};{pub_url}")

for artigo in artigos:
    
    buscar_link(artigo)
    time.sleep(60)
